name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run security scan weekly on Mondays at 9am
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: Check for outdated dependencies
      run: npm outdated || true

    - name: Run security linting
      run: npm run lint
      continue-on-error: true

    - name: Check TypeScript
      run: npx tsc --noEmit
      continue-on-error: true

